FROM loadimpact/k6:latest AS k6official

FROM golang:1.18.2

ARG SERVICE_NAME

COPY --from=docker:dind /usr/local/bin/docker /usr/local/bin/
COPY --from=k6official /usr/bin/k6 /usr/bin/k6

WORKDIR /${SERVICE_NAME}

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go install github.com/cosmtrek/air@latest

# For integration test
RUN apt-get update && apt-get install -y python3-pip && rm -rf /var/lib/apt/lists/*
RUN pip install jsonschema pyyaml

# Download vdp protocol YAML file
RUN mkdir /usr/local/vdp && curl https://raw.githubusercontent.com/instill-ai/vdp/main/protocol/vdp_protocol.yaml -so /usr/local/vdp/vdp_protocol.yaml

ENTRYPOINT ["tail", "-f", "/dev/null"]
