FROM loadimpact/k6:latest AS k6official

FROM golang:1.18.2

ARG SERVICE_NAME

COPY --from=docker:dind /usr/local/bin/docker /usr/local/bin/

COPY --from=k6official /usr/bin/k6 /usr/bin/k6

WORKDIR /${SERVICE_NAME}
COPY . /${SERVICE_NAME}

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go install github.com/cosmtrek/air@latest

RUN apt-get update && apt-get install -y python3-pip && rm -rf /var/lib/apt/lists/*

RUN pip install jsonschema pyyaml

ENTRYPOINT ["tail", "-f", "/dev/null"]
