ARG GOLANG_VERSION
FROM golang:${GOLANG_VERSION}

ARG SERVICE_NAME

COPY --from=docker:dind /usr/local/bin/docker /usr/local/bin/

WORKDIR /${SERVICE_NAME}

COPY go.mod go.sum ./
RUN go mod download
COPY . .

ARG TARGETOS TARGETARCH

# Install air
RUN --mount=target=. --mount=type=cache,target=/root/.cache/go-build --mount=type=cache,target=/go/pkg GOOS=$TARGETOS GOARCH=$TARGETARCH go install github.com/cosmtrek/air@latest

# Install k6
ARG K6_VERSION
ADD https://github.com/grafana/k6/releases/download/v${K6_VERSION}/k6-v${K6_VERSION}-linux-$TARGETARCH.tar.gz k6-v${K6_VERSION}-linux-$TARGETARCH.tar.gz
RUN tar -xf k6-v${K6_VERSION}-linux-$TARGETARCH.tar.gz --strip-components 1 -C /usr/bin

# For integration test
RUN apt-get update && apt-get install -y python3-pip && rm -rf /var/lib/apt/lists/*
RUN pip install jsonschema pyyaml

# Download vdp protocol YAML file
RUN mkdir /usr/local/vdp && curl https://raw.githubusercontent.com/instill-ai/vdp/main/protocol/vdp_protocol.yaml -so /usr/local/vdp/vdp_protocol.yaml

ENTRYPOINT ["tail", "-f", "/dev/null"]
