BEGIN;

ALTER TYPE valid_connector_type ADD VALUE IF NOT EXISTS 'CONNECTOR_TYPE_AI';
ALTER TYPE valid_connector_type ADD VALUE IF NOT EXISTS 'CONNECTOR_TYPE_BLOCKCHAIN';

CREATE TYPE valid_visibility AS ENUM (
  'VISIBILITY_UNSPECIFIED',
  'VISIBILITY_PRIVATE',
  'VISIBILITY_PUBLIC'
);

CREATE TYPE valid_task AS ENUM (
  'TASK_UNSPECIFIED',
  'TASK_CLASSIFICATION',
  'TASK_DETECTION',
  'TASK_KEYPOINT',
  'TASK_OCR',
  'TASK_INSTANCE_SEGMENTATION',
  'TASK_SEMANTIC_SEGMENTATION',
  'TASK_TEXT_TO_IMAGE',
  'TASK_TEXT_GENERATION'
);

ALTER TABLE public.connector ADD COLUMN "visibility" VALID_VISIBILITY DEFAULT 'VISIBILITY_PRIVATE' NOT NULL;
ALTER TABLE public.connector ADD COLUMN "task" valid_task DEFAULT 'TASK_UNSPECIFIED' NOT NULL;

DROP INDEX IF EXISTS unique_owner_id_connector_type_deleted_at;
CREATE UNIQUE INDEX unique_owner_id_deleted_at ON public.connector (owner, id) WHERE delete_time IS NULL;

COMMIT;
