server:
  privateport: 3082
  publicport: 8082
  https:
    cert:
    key:
  edition: local-ce:dev
  usage:
    enabled: true
    tlsenabled: true
    host: usage.instill.tech
    port: 443
  debug: true
  prebuiltconnector:
    enabled: false
connector:
  airbyte:
    mountsource:
      vdp: vdp # vdp docker volume name by default
      airbyte: airbyte # airbyte docker volume name by default
    mounttarget:
      vdp: /vdp
      airbyte: /local
    excludelocalconnector: false
database:
  username: postgres
  password: password
  host: pg-sql
  port: 5432
  name: connector
  version: 5
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30m # In minutes, e.g., '60m'
pipelinebackend:
  host: pipeline-backend
  publicport: 8081
  https:
    cert:
    key:
mgmtbackend:
  host: mgmt-backend
  privateport: 3084
  https:
    cert:
    key:
controller:
  host: controller-vdp
  privateport: 3085
  https:
    cert:
    key:
log:
  external: false
  otelcollector:
    host: otel-collector
    port: 8095
influxdb:
  url: http://influxdb:8086
  token: i-love-instill-ai
  org: instill-ai
  bucket: instill-ai
  flushinterval: 10 # In seconds for non-blocking batch mode
  https:
    cert:
    key:
