server:
  port: 8082
  https:
    cert:
    key:
  corsorigins:
  edition: local-ce:dev
  disableusage: false
  debug: true
worker:
  mountsource:
    vdp: vdp # vdp volume name
    airbyte: airbyte # airbyte volume name
database:
  username: postgres
  password: password
  host: pg-sql
  port: 5432
  name: connector
  version: 1
  timezone: Etc/UTC
  pool:
    idleconnections: 5
    maxconnections: 10
    connlifetime: 30m # In minutes, e.g., '60m'
temporal:
  clientoptions:
    hostport: temporal:7233
pipelinebackend:
  host: pipeline-backend
  port: 8081
  https:
    cert:
    key:
mgmtbackend:
  host: mgmt-backend
  adminport: 3084
  https:
    cert:
    key:
usagebackend:
  tlsenabled: true
  host: usage.instill.tech
  port: 443
